services:
  springboot-app:
    build: ./src/main-server/
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mydb
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=mypassword
      - MY_JWT_SECRET_KEY=7IIG2SJu8YGiDNPnZ4WQgfhCvI1xh1Kmwy6BVyJ7wd8=
      - MY_QUESTIONNAIRE_MODELPREDICTION_URL=http://model-service:5000/predict
    depends_on:
      - postgres
      - model-service
    networks:
      - shared-network

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - shared-network

  model-service:
    build: ./src/model-microservice/
    networks:
      - shared-network

volumes:
  pgdata:

networks:
  shared-network:
    driver: bridge
