name: project-1
channels:
  - defaults
dependencies:
  - python==3.12.4
  - flask
  - flask-cors=3.0.10
  - numpy
  - pandas
  - scikit-learn=1.5.1
  - seaborn
  - matplotlib
  - lightgbm
  - notebook
  - gunicorn
